version: '3'
services:
  redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"
  api:
    container_name: customers-management
    build: .
    restart: always
    image: customers-management
    ports:
      - "3333:3333"
    environment:
      - APP_PORT=${APP_PORT}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - REDIS_HOST=${REDIS_HOST}
    links:
      - redis
